/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef leaderboard_CONSTANTS_H
#define leaderboard_CONSTANTS_H

#include "leaderboard_types.h"



class leaderboardConstants {
 public:
  leaderboardConstants();

};

extern const leaderboardConstants g_leaderboard_constants;



#endif
